function GoBack() {
    $(window).scrollTop(0);
    $('#Blog_Page').show();
    $('#Top_Category_Blog_1').hide();
    $('#Top_Category_Blog_2').hide();
    $('#Top_Category_Blog_3').hide();
    $('#Top_Category_Blog_4').hide();
    $('#Stock_Market').hide();
    $('#Taxation').hide();
    $('#Latest_Blog_2').hide();
    $('#Latest_Blog_4').hide();
    $('#Latest_Blog_5').hide();
    $('#Latest_Blog_6').hide();
    $('#Latest_Blog_7').hide();
    $('#Latest_Blog_8').hide();
    $('#Latest_Blog_9').hide();
    $('#Latest_Blog_10').hide();
    $('#Latest_Blog_11').hide();
    $('#Latest_Blog_12').hide();
    $('#Top_Category_Blog_Page').hide();
    $('#Blog_of_First_Page').hide();
}

$(document).ready(function () {
    console.log("ready!");
    $('.navbar-toggler').on('click', function () {
        $('.navbar-collapse').toggle();
    })
    $('.dropdown-toggle').on('click', function () {
        $('.dropdown-menu').toggle();
    })
    $('.Top_Category').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').show();
        $('#Blog_of_First_Page').hide();
    })
    $('.Blog_first_page').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').show();
    })
    $('.Continue_reading_1').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').show();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('#Continue_reading_2').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').show();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('#Continue_reading_3').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').show();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('#Continue_reading_4').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').show();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();

    })
    $('.Continue_reading_5').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').show();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('#Continue_reading_6').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').show();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.TCI_brochure').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').show();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.SAME_MISTAKES_AGAIN_AND_AGAIN').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').show();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.Avoid_Penny_Stock').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').show();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.Position_sizing').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').show();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.Back_Testing').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').show();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.Risk_Management').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').show();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.how-to-focus-on-price-action-to-clear-the-noise').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').show();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.how-to-stop-over-trading').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').show();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.trading-too-complex-strategies-with-many-indicators').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').show();
        $('#Latest_Blog_12').hide();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
    $('.how-to-become-a-disciplined-trader').on('click', function () {
        $(window).scrollTop(0);
        $('#Blog_Page').hide();
        $('#Top_Category_Blog_1').hide();
        $('#Top_Category_Blog_2').hide();
        $('#Top_Category_Blog_3').hide();
        $('#Top_Category_Blog_4').hide();
        $('#Stock_Market').hide();
        $('#Taxation').hide();
        $('#Latest_Blog_2').hide();
        $('#Latest_Blog_4').hide();
        $('#Latest_Blog_5').hide();
        $('#Latest_Blog_6').hide();
        $('#Latest_Blog_7').hide();
        $('#Latest_Blog_8').hide();
        $('#Latest_Blog_9').hide();
        $('#Latest_Blog_10').hide();
        $('#Latest_Blog_11').hide();
        $('#Latest_Blog_12').show();
        $('#Top_Category_Blog_Page').hide();
        $('#Blog_of_First_Page').hide();
    })
});
